// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'key': string;
  'key--A': string;
  'key--A--sharp': string;
  'key--B': string;
  'key--C': string;
  'key--C--sharp': string;
  'key--D': string;
  'key--D--sharp': string;
  'key--E': string;
  'key--F': string;
  'key--F--sharp': string;
  'key--G': string;
  'key--G--sharp': string;
  'key--sharp': string;
  'keyboard': string;
  'keyboardContainer': string;
  'keyboardTop': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
